// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using onpmysql.DbData;

#nullable disable

namespace onpmysql.Migrations
{
    [DbContext(typeof(CsvDbContext))]
    [Migration("20250611191224_AzureMigrationOne")]
    partial class AzureMigrationOne
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZomatoDb.Models.ZomatoModelOne", b =>
                {
                    b.Property<int>("RestaurantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("restaurant_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RestaurantId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<double?>("AggregateRating")
                        .HasColumnType("float")
                        .HasColumnName("aggregate_rating");

                    b.Property<int?>("AverageCostForTwo")
                        .HasColumnType("int")
                        .HasColumnName("average_cost_for_two");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("City");

                    b.Property<int?>("CountryCode")
                        .HasColumnType("int")
                        .HasColumnName("country_code");

                    b.Property<string>("Cuisines")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("cuisines");

                    b.Property<string>("Currency")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("currency");

                    b.Property<string>("HasOnlineDelivery")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("has_online_delivery");

                    b.Property<string>("HasTableBooking")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("has_table_booking");

                    b.Property<string>("IsDeliveringNow")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("is_delivering_now");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double")
                        .HasColumnName("latitude");

                    b.Property<string>("Locality")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("locality");

                    b.Property<string>("LocalityVerbose")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("locality_verbose");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double")
                        .HasColumnName("longitude");

                    b.Property<int?>("PriceRange")
                        .HasColumnType("int")
                        .HasColumnName("price_range");

                    b.Property<string>("RatingColor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("rating_color");

                    b.Property<string>("RatingText")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("rating_text");

                    b.Property<string>("RestaurantName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("restaurant_name");

                    b.Property<string>("SwitchToOrderMenu")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("switch_to_order_menu");

                    b.Property<int?>("Votes")
                        .HasColumnType("int")
                        .HasColumnName("votes");

                    b.HasKey("RestaurantId");

                    b.ToTable("zomato_restaurants", (string)null);
                });

            modelBuilder.Entity("onpmysql.Models.Twitter", b =>
                {
                    b.Property<long>("C0")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("C0"));

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Geo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sentiment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("C0");

                    b.ToTable("twitter", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
