// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using onpmysql.DbData;

#nullable disable

namespace onpmysql.Migrations
{
    [DbContext(typeof(CsvDbContext))]
    [Migration("20250609060001_ZoamtoMigration")]
    partial class ZoamtoMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ZomatoDb.Models.ZomatoModelOne", b =>
                {
                    b.Property<int>("RestaurantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RestaurantId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("AggregateRating")
                        .HasColumnType("float");

                    b.Property<int?>("AverageCostForTwo")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("CountryCode")
                        .HasColumnType("int");

                    b.Property<string>("Cuisines")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Currency")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("HasOnlineDelivery")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("HasTableBooking")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("IsDeliveringNow")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double");

                    b.Property<string>("Locality")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LocalityVerbose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double");

                    b.Property<int?>("PriceRange")
                        .HasColumnType("int");

                    b.Property<string>("RatingColor")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RatingText")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RestaurantName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("RestaurantName");

                    b.Property<string>("SwitchToOrderMenu")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("Votes")
                        .HasColumnType("int");

                    b.HasKey("RestaurantId");

                    b.ToTable("ZomatotableEntity");
                });

            modelBuilder.Entity("onpmysql.Models.Twitter", b =>
                {
                    b.Property<long>("C0")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("C0"));

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<string>("Entities")
                        .HasColumnType("longtext");

                    b.Property<string>("Geo")
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<string>("Sentiment")
                        .HasColumnType("longtext");

                    b.Property<string>("Text")
                        .HasColumnType("longtext");

                    b.Property<string>("User")
                        .HasColumnType("longtext");

                    b.HasKey("C0");

                    b.ToTable("twitter", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
