// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using onpmysql.DbData;

#nullable disable

namespace onpmysql.Migrations
{
    [DbContext(typeof(CsvDbContext))]
    partial class CsvDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ZomatoDb.Models.ZomatoModelOne", b =>
                {
                    b.Property<long>("RestaurantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("restaurant_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("RestaurantId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<float?>("AggregateRating")
                        .HasColumnType("float")
                        .HasColumnName("aggregate_rating");

                    b.Property<long?>("AverageCostForTwo")
                        .HasColumnType("bigint")
                        .HasColumnName("average_cost_for_two");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("City");

                    b.Property<long?>("CountryCode")
                        .HasColumnType("bigint")
                        .HasColumnName("country_code");

                    b.Property<string>("Cuisines")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cuisines");

                    b.Property<string>("Currency")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("currency");

                    b.Property<string>("HasOnlineDelivery")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("has_online_delivery");

                    b.Property<string>("HasTableBooking")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("has_table_booking");

                    b.Property<string>("IsDeliveringNow")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("is_delivering_now");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double")
                        .HasColumnName("latitude");

                    b.Property<string>("Locality")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("locality");

                    b.Property<string>("LocalityVerbose")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("locality_verbose");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double")
                        .HasColumnName("longitude");

                    b.Property<long?>("PriceRange")
                        .HasColumnType("bigint")
                        .HasColumnName("price_range");

                    b.Property<string>("RatingColor")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("rating_color");

                    b.Property<string>("RatingText")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("rating_text");

                    b.Property<string>("RestaurantName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("restaurant_name");

                    b.Property<string>("SwitchToOrderMenu")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("switch_to_order_menu");

                    b.Property<long?>("Votes")
                        .HasColumnType("bigint")
                        .HasColumnName("votes");

                    b.HasKey("RestaurantId");

                    b.ToTable("zomatorestaurants", (string)null);
                });

            modelBuilder.Entity("onpmysql.Models.Twitter", b =>
                {
                    b.Property<long>("C0")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("C0"));

                    b.Property<string>("Country")
                        .HasColumnType("longtext")
                        .HasColumnName("country");

                    b.Property<string>("Entities")
                        .HasColumnType("longtext")
                        .HasColumnName("entities");

                    b.Property<string>("Geo")
                        .HasColumnType("longtext")
                        .HasColumnName("geo");

                    b.Property<string>("Location")
                        .HasColumnType("longtext")
                        .HasColumnName("location");

                    b.Property<string>("Sentiment")
                        .HasColumnType("longtext")
                        .HasColumnName("sentiment");

                    b.Property<string>("Text")
                        .HasColumnType("longtext")
                        .HasColumnName("text");

                    b.Property<string>("User")
                        .HasColumnType("longtext")
                        .HasColumnName("user");

                    b.HasKey("C0");

                    b.ToTable("twitter", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
