// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using onpmysql.DbData;

#nullable disable

namespace onpmysql.Migrations
{
    [DbContext(typeof(CsvDbContext))]
    partial class CsvDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("onpmysql.Models.Twitter", b =>
                {
                    b.Property<long>("C0")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<string>("Entities")
                        .HasColumnType("longtext");

                    b.Property<string>("Geo")
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<string>("Sentiment")
                        .HasColumnType("longtext");

                    b.Property<string>("Text")
                        .HasColumnType("longtext");

                    b.Property<string>("User")
                        .HasColumnType("longtext");

                    b.HasKey("C0");

                    b.ToTable("twitter", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
